### ISSUE TITLE
How to evaluate on multiple gpus ？

### ISSUE THREAD

**Issue by FiveLu** [tusen-ai/Anchor3DLane#11]
Hi, i was replicating your experiments recently and got errors when I run  `dist_test.sh` for multi-GPU eval (single gpu eval is normal).
I saw `workflow = [('train', 10000000)]` in configs, that seems to be avoiding the multi-gpu evaluation process.
So, what's the problem and how to fix it? 

Thanks a lot.

**Comment by spyflying** [comment]
Sorry that our code currently does not support multiple gpu testing or testing during training for now. If you want to conduct multi-gpu testing, you can refer to the code of multi_gpu_test function in apis/test.py to collect results from multiple gpus. We will also update these functions later.

**Comment by spyflying** [comment]
We have added the code for multi-gpu testing in the latest commitment. You may re-clone the codes to check if it works.
