### ISSUE TITLE
使用openlane.py脚本划分Openlane 数据集问题

### ISSUE THREAD

**Issue by CHANGgreenEVER** [tusen-ai/Anchor3DLane#14]
您好，使用你们提供的openlane.py划分Openlane 数据集出现了一些问题，在使用--merge和--genrate后，data-lists文件中train.txt文件中只剩一行信息，如图：
![image](https://github.com/tusen-ai/Anchor3DLane/assets/108571143/860f3b49-32f6-4dcf-b3d9-efdb4fef6d42)
生成的cache_dense文件夹中的pkl格式文件似乎不完整，开始训练时，出现：
![image](https://github.com/tusen-ai/Anchor3DLane/assets/108571143/e5f058b3-8d38-473e-94aa-b872ae02c704)
似乎你们的openlane.py有一些问题，希望你们的回复，谢谢！

**Comment by spyflying** [comment]
感谢你的提醒。我们之前提供的openlane.py存在一点问题，现在我们已经修复了。你在训练中遇到的错误应该不是pickle文件造成的，可能是data list不完整导致的。你可以用新的openlane.py生成的数据再训练一下，看是否还会遇到相同的问题。

**Comment by CHANGgreenEVER** [comment]
修改后的openlane.py生成的数据可以正常训练，感谢你们的工作！还有一个问题，若想测试openlane数据集中各场景得分，该如何做？

**Comment by spyflying** [comment]
在config的test中添加“test_list"字段为对应场景的text list，如test_list="lane3d_1000/test/1000_curve.txt"，之后再运行evaluation即可。

**Comment by CHANGgreenEVER** [comment]
是在这里加吗?
![image](https://github.com/tusen-ai/Anchor3DLane/assets/108571143/bc103874-2bae-476d-b737-a63c2cf32d62)
似乎不对，可以在详细说明一下吗，感谢！

**Comment by spyflying** [comment]
是这样的，你行末少了个逗号：
    test=dict(
        type=dataset_type,
        data_root=data_root,
        y_steps=anchor_y_steps,
        data_list='validation.txt',
        test_list="lane3d_1000/test/1000_curve.txt",
        dataset_config=dataset_config, 
        test_mode=True,
        pipeline=test_pipeline)
