### ISSUE TITLE
incorrect testing results

### ISSUE THREAD

**Issue by qiang-sean-liu** [tusen-ai/Anchor3DLane#26]
I ran testing on Apollosim dataset, but got results that did not make any sense. The classification scores were all around 0.5, so if the prob_th set to 0.7 as default, there were no lanes detected.

The model apollo_anchor3dlane.pth was used for testing, which was downloaded from the model zoo https://pan.baidu.com/s/1HPYxsNNSOO5CY7-RwAt9cw?pwd=bqvy.

There was a warning during testing:
'''
load checkpoint from local path: ./pretrained/apollo_anchor3dlane.pth
The model and loaded state dict do not match exactly

missing keys in source state_dict: cls_layer.1.layer.0.weight, cls_layer.1.layer.0.bias, cls_layer.1.layer.2.weight, cls_layer.1.layer.2.bias, cls_layer.1.layer.4.weight, cls_layer.1.layer.4.bias, reg_x_layer.1.layer.0.weight, reg_x_layer.1.layer.0.bias, reg_x_layer.1.layer.2.weight, reg_x_layer.1.layer.2.bias, reg_x_layer.1.layer.4.weight, reg_x_layer.1.layer.4.bias, reg_z_layer.1.layer.0.weight, reg_z_layer.1.layer.0.bias, reg_z_layer.1.layer.2.weight, reg_z_layer.1.layer.2.bias, reg_z_layer.1.layer.4.weight, reg_z_layer.1.layer.4.bias, reg_vis_layer.1.layer.0.weight, reg_vis_layer.1.layer.0.bias, reg_vis_layer.1.layer.2.weight, reg_vis_layer.1.layer.2.bias, reg_vis_layer.1.layer.4.weight, reg_vis_layer.1.layer.4.bias
'''

Is this the underlining problem? Please advise on how to fix this.

Thanks!

**Comment by spyflying** [comment]
It seems that you have used an unmatched config file. The checkpoint you used corresponds to this file: configs/apollosim/anchor3dlane.py. If you'd like to use configs/apollosim/anchor3dlane_iter.py during testing, you'll have to download this checkpoint: https://pan.baidu.com/s/1f4Ssts_cUU7kGtXUyRulLA?pwd=pfe5
