### ISSUE TITLE
question about the ablation experiment

### ISSUE THREAD

**Issue by koughua** [tusen-ai/Anchor3DLane#3]
Thanks for your amazing work!

Im very confuse about your ablation experiment in Table 5, you mention: including **warping** FV image to BEV image (line 1) and warping FV feature to BEV feature (line 2), and keep the other settings same as our original Anchor3DLane. 

I want to know hou you warp the image or feature, is use the IPM method, use matrix sampling form orig image? or just use a Linear Layer like nn.Linear(input_h*input_w, output_h*output_w)?

did the code contain this part of experiment?

**Comment by spyflying** [comment]
We use the IPM method, i.e., the homography matrix calculated with camera parameters, to warp the FV images/features to the BEV space. The warping codes are borrowed from [CLGo](https://github.com/liuruijin17/CLGo/blob/406e22848325602b0e86b2766d8dc6d1c53247aa/models/py_utils/kp_pt_joint.py#L436).
