### ISSUE TITLE
Error occured while reproducing result

### ISSUE THREAD

**Issue by wanyunfeiAlex** [tusen-ai/Anchor3DLane#6]
Hello, thanks for your great work. I am reproducing this code but some errors spurted out. It complained while training:
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [0,0,0], thread: [7,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [0,0,0], thread: [9,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [0,0,0], thread: [11,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.

![image](https://github.com/tusen-ai/Anchor3DLane/assets/103512879/727256c6-7f08-4919-bf06-39a8daa27b5e)

I used the openLane dataset, and tried training with configs "anchor3dlane_effb3.py" & "anchor3dlane_iter.py", neither trained some iters and end up failing, throwing the errors mentioned above.

Noted that the openLane dataset seems not coincide with this code at first(which was also complained about in another open issue: https://github.com/tusen-ai/Anchor3DLane/issues/5). So I reconstructed  "data_lists/traning.txt" and "data_lists/validation.txt" w.r.t the file lists in cache_dense to circumvent the file-missing-error, and I ended up here.

I assume that this index-exceeding error is the result of different versions of the openLane datasets and there might be some hard-coded index that causes this error?

**Comment by spyflying** [comment]
This error is caused by abnormal lane categories, e.g., more than 21 or less than 0. You can check your generated pickle files in the training set and exclude the abnormal ones. PS As far as I know, training/segment-1926967104529174124_5214_780_5234_780_with_camera_labels/150914294030533900.pkl contains abnormal label in both versions of openlane.
