### ISSUE TITLE
关于等宽约束的问题

### ISSUE THREAD

**Issue by laqangela** [tusen-ai/Anchor3DLane#7]
你好！我有个问题想请教一下！
论文3.4节等宽约束优化这里，宽度是如何计算的，我没读懂您的公式9-11，请问您可以解答一下吗～
<img width="374" alt="截屏2023-05-27 18 00 02" src="https://github.com/tusen-ai/Anchor3DLane/assets/107610775/06275bd6-31c1-4434-ae52-701dfce2d0f0">
<img width="445" alt="截屏2023-05-27 18 56 00" src="https://github.com/tusen-ai/Anchor3DLane/assets/107610775/b2779e6e-c7f2-4aff-b459-61f5046747ca">
我自己画了一个图，不知道我的理解是不是对的：
![IMG_2351](https://github.com/tusen-ai/Anchor3DLane/assets/107610775/a02e4644-1c91-4ece-b177-cdf043eb16ec)
θjk指的是一条车道线预测和Yg轴的夹角吗？论文中说是法向方向。

**Comment by spyflying** [comment]
是这样的，因为车道线通常是一条曲线，因此θ_j^k是在车道线在点P‘_j^k（即调整后的点P_j^k）的处的切线与y轴的夹角。
公式9计算了调整后的两条车道线在不同y坐标处的宽度，公式11约束不同y坐标处的宽度与它们的均值的差距尽可能小，即约束不同y坐标处等宽，公式10的第二项是正则项，使得通过尽可能小的调整达到等宽。
