### ISSUE TITLE
新Openlane v2 数据集训练问题

### ISSUE THREAD

**Issue by CHANGgreenEVER** [tusen-ai/Anchor3DLane#9]
您好，请问使用新发布的Openlane v2版本数据集的目录结构依然是你们展示的以下结构吗?
![image](https://github.com/tusen-ai/Anchor3DLane/assets/108571143/67e8283f-af32-4ca7-be92-92ca61fd83d8)
同时，我并没有在下载好的Openlane v2中找到对应data_splits/文件夹

**Comment by spyflying** [comment]
是的。data_splits、cache_dense、data_lists需要通过tools/convert_datasets/openlane.py生成
